### PR TITLE
Synchronize mgr_change2 feature branch with master as of CleverRaven commit f2bd6e3

### PR DESCRIPTION
**Pull request by ArtemisDimikaelo**
#### Purpose of change
Merges master branch (pulled from CleverRaven CDDA as of commit f2bd6e3 on 9 April 2019) into mgr_change2, keeping mgr_change2 updated.

### CODE REVIEW

**Comment by Firestorm01X2** [comment]
Hello. 
You are probably did PR for wrong repostiry.
Thank you for onributing, anyway :)

**Comment by ArtemisDimikaelo** [comment]
Hey! No, I just wanted to see if I could contribute somehow to this PR for the evolution feature - and I was already going to fork and merge anyway so I could build my own copy to test the feature out and report if there's any bugs. I apologize if it wasn't necessary!

**Comment by Firestorm01X2** [comment]
>Hey! No, I just wanted to see if I could contribute somehow to this PR for the evolution feature - and I was already going to fork and merge anyway so I could build my own copy to test the feature out and report if there's any bugs. I apologize if it wasn't necessary!

No problem. But since there is +16 000 lines then something with merge gone really wrong. +16 000 line is unrewievable.

About incorporating - I dont think that is is good idea to merge something in my PR *right now*. It is better to do it later then it will be (if ever) merged to main repository.

But if you want to try offer **small** imporvements then can try review it. And maybe merge it. But as I said - no gurantees.

**Comment by Firestorm01X2** [comment]
>+19,363 −17,320 

Something is gone really wrong with merges.
I literally can't look at it.

I  still recommend for you to hold off until it will be merged in main repository and then create PR to there.

But anyway for now just explain what are you trying to do (change or maybe add something)?

**Comment by ArtemisDimikaelo** [comment]
Hey,

I apologize again for causing any inconvenience. What I was intending to do was helping by updating the branch with the [CleverRaven Cataclysm repo's](https://github.com/CleverRaven/Cataclysm-DDA/) latest changes. However, I can absolutely see how it would be a big burden to verify the changes, and it's not feasible to do so, especially for a private branch. I'm sorry for any inconvenience, again.

**Comment by Firestorm01X2** [comment]
>I'm sorry for any inconvenience, again.

No problem :)

**Pull request closed without merging**
